### ISSUE TITLE
i cant draw

### ISSUE THREAD

**Issue by johnfelipe** [459below/draw#9]
![pantallazo-0350](https://user-images.githubusercontent.com/428820/31024810-da2380ac-a505-11e7-8e27-b6f2a0f59bde.png)

i cant select icons and cant draw

```
start...
DirtyDB is used. This is fine for testing but not recommended for production.
Access Etherdraw at http://0.0.0.0:9002
Socket disconnected
```

**Comment by 459below** [comment]
Support requests are not issues.
